import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for LinkRescue.io',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <div className="prose prose-invert max-w-none">
        <p><em>Last updated: February 27, 2026</em></p>
        <p>This is a placeholder for your Terms of Service. You should replace this with a comprehensive policy generated by a service like Termly or Iubenda.</p>
        <p>Please read these terms and conditions carefully before using Our Service.</p>
      </div>
    </div>
  );
}
