import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for LinkRescue.io',
};

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <div className="prose prose-invert max-w-none">
        <p><em>Last updated: February 27, 2026</em></p>
        <p>This is a placeholder for your Privacy Policy. You should replace this with a comprehensive policy generated by a service like Termly or Iubenda.</p>
        <p>We respect your privacy and are committed to protecting it. This Privacy Policy explains our policies and procedures on the collection, use and disclosure of your information when you use the Service.</p>
      </div>
    </div>
  );
}
