-- LinkRescue CMS — publish 3 evergreen posts (2026-07-08)
-- Target: linkrescue Supabase project (skclpvjkvlqwvkmffemy) -> SQL Editor
-- Safe to re-run: ON CONFLICT (slug) DO UPDATE. Generated by scripts/generate-blog-inserts.js

INSERT INTO blog_posts (
  slug, title, author, tags, category, seo_title, meta_description, content, status, sites, published_at
) VALUES (
  'best-affiliate-link-checker-2026',
  'Best Affiliate Link Checker 2026: 8 Tools Compared (Honest Breakdown)',
  'Carson Roell',
  ARRAY['affiliate link checker','broken link monitor','affiliate marketing tools','link rot','SaaS comparison'],
  'comparisons',
  'Best Affiliate Link Checker 2026: 8 Tools Compared',
  '8 affiliate link checkers compared in 2026 — LinkWhisper, Pretty Links, Affilimate, AMZ Watcher, and more. Honest breakdown of which tool fits your stack, budget, and scale.',
  $lr_best_affiliate_link_$If you run an affiliate site, you already know link rot is eating your revenue. Amazon ASINs churn, merchants close programs, affiliate networks rebrand their redirect domains — and every broken link is a click that converts to zero.

The question isn't whether you need monitoring. The question is: **which tool actually fits your stack, your budget, and the scale you're operating at?**

This post compares eight affiliate link checkers on what actually matters: what each tool monitors, what it misses, what it really costs at a realistic site size, and which situations it wins. It draws on each vendor's published pricing and docs, their free tiers and trials, and what we've learned running a crawler across 6,550 affiliate links a month for the public [Link Rot Index](/blog/link-rot-index-june-2026).

I run LinkRescue — so yes, I'm biased. I tried to counter that by giving every competitor a real chance to win its category. Wherever another tool is better for your use case, I say so.

## The Shortlist

| Tool | Best for | Pricing | Platform |
|---|---|---|---|
| **LinkWhisper** | Solo WordPress bloggers | $97–$497/yr | WordPress plugin |
| **Pretty Links** | WordPress sites with a link-cloaking focus | Free – $199/yr | WordPress plugin |
| **Affilimate** | Analytics + attribution (not monitoring) | $49–$399/mo | Web app |
| **AMZ Watcher** | Amazon-only affiliates | $24/mo | Web app |
| **Lasso** | Display-focused Amazon affiliates | $39+/mo | WordPress plugin |
| **24metrics** | Enterprise affiliate networks | Custom | Web app |
| **LynkDog** | Backlink/outbound link monitoring | $29+/mo | Web app |
| **LinkRescue** | Multi-site, agencies, non-WordPress stacks | Free / $29 / $79/mo | Web app + API + CLI |

Below is the detailed breakdown, followed by a "best for your situation" guide at the end.

---

## How I Compared Them

Every tool below is scored against the same eight questions, using its published pricing, docs, and free tier or trial where one exists:

1. **What does it actually detect?** — broken links only, or the failure modes that matter (Amazon OOS, dead merchants, redirect chains that strip your affiliate tag)
2. **What does it structurally miss?** — every tool has a blind spot; the vendor won't tell you, this post will
3. **Platform lock-in** — WordPress plugin vs. works-anywhere
4. **Multi-site support** — can it handle an agency managing 5-10 sites?
5. **Developer / automation features** — API, CLI, CI/CD, webhook support
6. **Pricing reality** — actual monthly cost for a realistic site size
7. **Alert quality** — actionable alerts or noise, per user reports and our own trials
8. **Who it's genuinely best for** — every tool here wins *some* situation

One data point to hold in mind while you read: in our June 2026 study of 50 established affiliate sites (6,550 links checked), **9.1% of links had broken affiliate attribution — the link "works" but the tag is gone — versus 5.8% that were visibly broken.** The failure mode most tools don't check for is the most common one. Ask of every tool below: does it follow the redirect chain and verify the tag survives?

---

## 1. LinkWhisper — $97–$497/yr

LinkWhisper is primarily an internal-linking plugin, with broken-link monitoring bolted on. It scans outbound (and internal) links periodically and reports 404s inside the WordPress dashboard.

**What it does well:**
- Deeply integrated into WordPress — zero friction if you're already there
- Internal-linking suggestions are genuinely useful (the original product) and pair well with broken-link detection
- Annual pricing with 60-day money-back — low commitment
- Multisite license available at the Network tier

**Where it falls short:**
- WordPress-only. If you run Next.js, Ghost, Webflow, or anything else, LinkWhisper is off the table.
- External-link monitoring feels like a secondary feature. The detection is solid but alerting + remediation UX lags behind dedicated tools.
- No API, no CLI, no CI integration. It's a plugin, not a platform.
- No Amazon-specific ASIN monitoring (OOS state, pricing changes, etc.)
- Annual-only billing at the Pro tiers — no monthly option

**Verdict:** If you're a WordPress solo blogger and want internal-linking + basic external broken-link detection in one tool, LinkWhisper is a legitimate one-stop buy. If you need dedicated monitoring or operate outside WordPress, look elsewhere.

---

## 2. Pretty Links — Free – $199/yr

Pretty Links is a link-cloaking + redirect-management tool that added automatic broken-link scanning in recent versions. If you already cloak all your affiliate links through Pretty Links redirects (`yoursite.com/go/merchant`), it can monitor the downstream targets and alert you when they break.

**What it does well:**
- Free tier is generous for small sites
- If you already use Pretty Links for cloaking, the monitoring is "free" from a workflow perspective
- Alerts fire when redirect targets return non-2xx
- Automatic broken-link scans for high-converting links (Pro tier)

**Where it falls short:**
- Only monitors links that go through Pretty Links redirects. Direct affiliate links on your pages aren't tracked.
- WordPress-only
- The monitoring layer feels like a feature, not a product — the primary use case is still link management
- No agency features (multi-site dashboard)
- No API / CLI

**Verdict:** Excellent value if you're already a Pretty Links user and want basic monitoring as a bundled extra. Not a standalone solution.

---

## 3. Affilimate — $49–$399/mo

This one gets miscategorized often: **Affilimate is an analytics and attribution tool, not a link monitor.** It aggregates data from 100+ affiliate networks, gives you heatmaps, SKU-level attribution, and revenue dashboards.

**What it does well:**
- Best-in-class affiliate analytics — if you want to see which links actually convert, which pages drive revenue, which SKUs underperform, this is the tool
- Data aggregation across Amazon, CJ, Impact, ShareASale, Awin, Partnerize, and 100+ more
- SKU-level attribution is rare in this price range
- Works with any platform (WordPress, Ghost, Next.js, headless)

**Where it falls short:**
- **It doesn't actively monitor for broken links.** That's not its job. If you buy Affilimate expecting monitoring alerts, you'll be disappointed.
- Price jumps fast: $49 Starter → $99 Pro → $399 Scale. Real publishers with multiple networks often need Pro.
- Requires integration with each affiliate platform — setup time is non-trivial
- Overlap with LinkRescue is small; these are complementary tools more than competitors

**Verdict:** If your problem is "I don't know which links are making money," buy Affilimate. If your problem is "which links are silently broken," buy a dedicated monitor. Many serious affiliates run both.

---

## 4. AMZ Watcher — $24/mo

AMZ Watcher is an Amazon-only tool. It monitors Amazon ASINs for out-of-stock state, price changes, review count changes, and broken ASINs. That's it. That's the tool.

**What it does well:**
- Narrow focus = high-quality alerts for Amazon affiliates
- ASIN out-of-stock detection is the feature most generalist tools miss
- Cheapest tool on this list — $24/mo for unlimited ASIN monitoring on smaller plans
- Works with any site platform — it monitors Amazon, not your site

**Where it falls short:**
- Amazon only. Zero use if you also promote ShareASale, Impact, CJ, private offers, or any non-Amazon network.
- No site-crawling — you have to tell it which ASINs to monitor, or connect your Amazon affiliate account
- No agency multi-site UI
- Interface is utilitarian (not a criticism if you don't care)

**Verdict:** If Amazon is 80%+ of your affiliate revenue, AMZ Watcher is an obvious buy at $24/mo. If you have a mixed network portfolio, you need something broader alongside it.

---

## 5. Lasso — $39+/mo

Lasso is a display-and-promotion tool for Amazon affiliates — it creates pretty product display boxes, comparison tables, and handles Amazon link management. Broken-link alerts come as part of the Amazon management layer.

**What it does well:**
- Beautiful display components that typically lift CTR
- Amazon link refresh + monetization opportunities (suggests related products when one goes OOS)
- Broken Amazon link alerts are real and actionable
- Strong WordPress integration

**Where it falls short:**
- WordPress-first (though web-app components exist)
- Primary use case is display, not monitoring — monitoring is the supporting feature
- Amazon-leaning — non-Amazon networks are second-class citizens
- Price scales with features; if you only want monitoring, you're paying for display features you won't use

**Verdict:** Great buy if you want Amazon display + basic monitoring in one tool. Not the right fit if pure monitoring is the goal.

---

## 6. 24metrics Affiliate Link Checker — Custom pricing

24metrics targets the enterprise/network tier. Their affiliate link checker runs geo-simulated tests, device-specific rendering, deeplink validation, and rebrokering logic. This is what CJ, Impact-scale networks use to audit their merchant inventory.

**What it does well:**
- Geo + device testing — critical for offers with country-specific landing pages
- Deeplink validation (mobile app deep links, not just web URLs)
- Enterprise-grade reporting and SLAs
- API-first

**Where it falls short:**
- **Priced for enterprise.** If you're a $5K-50K/mo affiliate publisher, 24metrics will quote you a number that assumes you're a network, not a site owner.
- Overkill feature set for most publishers
- Setup complexity matches enterprise pricing

**Verdict:** If you're running an affiliate network with thousands of merchants, 24metrics is a real contender. If you're a publisher or an agency under ~$500K/yr in revenue, this is not your tool.

---

## 7. LynkDog — $29+/mo

LynkDog watches outbound links across 200+ affiliate platforms, but its angle is backlink/anchor/nofollow monitoring — it notices when a link changes anchor text, gets marked nofollow, or gets removed entirely.

**What it does well:**
- Detects nofollow attribute changes (most tools miss this)
- Monitors 200+ platforms
- Useful for SEO-focused affiliates watching their backlinks AND their own outbound affiliate links
- Reasonably priced for the depth

**Where it falls short:**
- Unique positioning (backlink-flavored) means some common affiliate use cases get less attention
- UI is more SEO-tool than publisher-tool
- Smaller user base — less community content, fewer tutorials

**Verdict:** If you care about backlink monitoring AND outbound affiliate link health, LynkDog does both. If you just want dedicated affiliate link monitoring, a more focused tool will serve you better.

---

## 8. LinkRescue — Free / $29 / $79/mo

Full disclosure: this is our tool. I'll keep this section honest — here's what we do well and where we don't fit.

**What we do well:**
- **Platform-agnostic.** Scan any site — WordPress, Ghost, Next.js, Webflow, headless, custom — we don't care what's underneath.
- **Multi-site from day one.** The $79 Agency tier is designed for agencies and portfolio publishers running 5-10+ sites from one dashboard.
- **Developer-friendly stack.** REST API (`/api/v1/`), CLI (`npx linkrescue scan yoursite.com`), GitHub Action for CI/CD, TypeScript SDK.
- **AI-powered suggestions.** When a link breaks, Claude-powered analysis suggests likely alternatives (new ASIN, replacement product, redirect target).
- **Revenue estimator.** Pro tier shows estimated revenue impact per broken link, based on page traffic and historical click-through.
- **Free scan tool.** You can scan any site without signing up at [linkrescue.io/free-scan](https://linkrescue.io/free-scan). This isn't a trial — it's a real tool. We use it to prove value before asking for money.

**Where we don't fit:**
- We're not the best pick for a WordPress solo blogger who also wants internal-linking suggestions — **use LinkWhisper instead.**
- We don't do affiliate analytics or attribution — **use Affilimate for that.**
- We don't do pretty product display boxes — **use Lasso for that.**
- We're not priced for enterprise networks — **24metrics is your tier.**
- We don't do link cloaking / redirect management — that's a different category (Pretty Links, ThirstyAffiliates, etc.)

**Verdict:** If you run multiple affiliate sites on a non-WordPress stack, or you're an agency, or you want API + CLI + CI integration alongside a clean web dashboard, LinkRescue is built for you. If you're a WordPress solo publisher, LinkWhisper or Pretty Links are likely a better fit.

---

## Best For Your Situation

**You're a WordPress solo blogger with one site (<200 pages):**
→ LinkWhisper or Pretty Links. Bundle monitoring into your existing WordPress workflow.

**You're an Amazon affiliate (80%+ of revenue from Amazon Associates):**
→ AMZ Watcher ($24/mo) is a no-brainer. Add Lasso if you want display boxes.

**You're a data-driven publisher who wants to know which links convert:**
→ Affilimate. You'll also want a dedicated monitor alongside it (we'd say us, but even free Pretty Links is better than nothing).

**You run 3+ affiliate sites, or you're an agency managing client sites:**
→ LinkRescue Agency tier ($79/mo). Multi-site dashboards are rare and ours is purpose-built for this.

**Your stack isn't WordPress (Ghost, Next.js, Webflow, headless):**
→ LinkRescue, Affilimate, or 24metrics — all work anywhere. Avoid WordPress-only tools.

**You need CI/CD integration or programmatic scans:**
→ LinkRescue (our API + CLI + GitHub Action are the most developer-forward in this space).

**You're an affiliate network or have enterprise-scale needs:**
→ 24metrics. Don't try to stretch a publisher-tier tool.

**You care about backlink anchor/nofollow changes AND broken affiliate links:**
→ LynkDog is a legitimate one-tool answer.

---

## FAQ

**Q: Can I just use Google Search Console or Ahrefs for this?**
No. GSC reports crawl errors on your own pages, not the health of outbound affiliate links. Ahrefs' Site Audit flags external 404s but doesn't track affiliate-specific state (Amazon OOS, merchant programs closing, geo-restrictions). Dedicated tools exist because this is a distinct job.

**Q: How often should I scan?**
Weekly minimum for most publishers. Daily if you're running seasonal or time-sensitive content (holiday guides, limited-time offers). Amazon affiliates should do daily — ASIN state changes hourly.

**Q: What's a realistic number of broken links on an active affiliate site?**
Our [June 2026 Link Rot Index](/blog/link-rot-index-june-2026) (50 established sites, 6,550 links) measured 5.8% flat-out broken plus 9.1% with broken affiliate attribution — and the median site had 27 issues. Only 3 of 34 fully-crawlable sites were clean. Every month without monitoring = more compound rot.

**Q: Do free scan tools actually work, or are they upsell traps?**
The good ones actually work. [LinkRescue's free scan](https://linkrescue.io/free-scan) returns a real report with no signup required. We use it as a distribution tool, not a bait-and-switch. Check it against any site before buying any paid tool.

**Q: How do I know which tool will actually fit my workflow before committing?**
Start with the free tiers (LinkWhisper 60-day money-back, Pretty Links free, LinkRescue free scan, AMZ Watcher 7-day trial). Run the same test site through 2-3 candidates before paying. The best tool on paper isn't always the best fit for your specific stack.

---

## The Bottom Line

The "best affiliate link checker" depends entirely on your situation. WordPress solo bloggers don't need the same tool as a five-site agency. Amazon-only publishers don't need what a multi-network SEO-focused site needs.

**My shortlist:**

- **Solo WordPress blogger:** LinkWhisper
- **Amazon-only:** AMZ Watcher
- **Multi-site / agency / non-WordPress / dev-friendly stack:** LinkRescue
- **Data + attribution:** Affilimate (pair with a dedicated monitor)
- **Enterprise:** 24metrics

Whatever you pick, stop leaving broken links live. Every broken affiliate link is a zero-revenue click, and most active sites have dozens live right now.

---

**Want to see what's broken on your site right now?** Run a free scan — no signup, no credit card. [linkrescue.io/free-scan](https://linkrescue.io/free-scan) scans up to 200 pages and shows you every broken affiliate link in under 2 minutes.

*Last updated: July 2026. Pricing and feature details were checked against vendor sites in April 2026 — confirm current numbers on each vendor's pricing page before buying.*
$lr_best_affiliate_link_$,
  'published',
  ARRAY['linkrescue'],
  now()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  tags = EXCLUDED.tags,
  category = EXCLUDED.category,
  seo_title = EXCLUDED.seo_title,
  meta_description = EXCLUDED.meta_description,
  content = EXCLUDED.content,
  status = EXCLUDED.status,
  sites = EXCLUDED.sites,
  published_at = COALESCE(blog_posts.published_at, EXCLUDED.published_at);

INSERT INTO blog_posts (
  slug, title, author, tags, category, seo_title, meta_description, content, status, sites, published_at
) VALUES (
  'silent-revenue-killer',
  'The Silent Revenue Killer: How Broken Affiliate Links Are Stealing Your Commissions',
  'Carson Roell',
  ARRAY['affiliate marketing','link rot','revenue optimization','affiliate links','passive income'],
  'affiliate-marketing',
  'The Silent Revenue Killer: How Broken Affiliate Links Cost You Money',
  'Discover how link rot silently drains affiliate revenue. Learn what causes broken links, calculate your potential losses, and protect your passive income with simple monitoring strategies.',
  $lr_silent_revenue_kille$You wake up, check your affiliate dashboard, and see... nothing new. Again.

But here's the uncomfortable truth: you might have earned commissions yesterday. The clicks were there. The buyer intent was real. But your affiliate link? It was broken. Dead. Sending potential customers into the digital void.

Welcome to the world of link rot — the silent revenue killer that affects every affiliate marketer, content creator, and niche site owner. And the worst part? Most people don't even know it's happening.

This isn't hypothetical. In our [June 2026 Link Rot Index](/blog/link-rot-index-june-2026) — 50 established affiliate sites, 6,550 links checked — 5.8% of links were flat-out broken and **9.1% had broken affiliate attribution** (the link resolves, the reader lands, the commission never fires). The median site had 27 issues. Only 3 of the 34 fully-crawlable sites were clean.

## What Exactly Is Link Rot?

Link rot (also called "link death" or "reference rot") is what happens when a hyperlink stops working. The page it pointed to no longer exists, was moved, or is temporarily unavailable. For regular web users, it's an annoyance. For affiliate marketers, it's a direct hit to your bottom line.

When someone clicks your affiliate link and hits a 404 error, a "product no longer available" page, or an out-of-stock message, you don't just lose that sale. You lose the trust of that reader. You lose the compound effect of that content working for you 24/7. You lose money you didn't even know you could have made.

## Why Do Affiliate Links Break?

Understanding the enemy is the first step to defeating it. Here are the most common causes of affiliate link rot:

### 1. Product Discontinuation

Amazon alone discontinues thousands of products every month. When a product is removed from a retailer's catalog, your affiliate link often goes with it. That detailed review you wrote? Still ranking. Still getting traffic. But now it's a dead end.

### 2. URL Structure Changes

Retailers frequently update their URL structures. A product might move from `/dp/B08N5WRWNW` to `/dp/B08N5WRWNW/ref=...` or be reorganized into a different category. Your old link might redirect — or it might not.

### 3. Out-of-Stock Items

Some retailers remove product pages entirely when items go out of stock. Others redirect to generic category pages without preserving your affiliate tracking. Either way, your commission potential vanishes.

### 4. Affiliate Program Changes

Networks change. Tracking parameters get updated. Sometimes entire programs shut down. That affiliate link you carefully placed three months ago? It might be pointing to nothing.

### 5. Website Migrations

When retailers redesign their sites or switch e-commerce platforms, URLs often break in the process. What worked yesterday might not work today.

## The Real Cost: Let's Do The Math

Link rot isn't just a technical nuisance — it's a measurable revenue drain. Let's look at some realistic scenarios:

### Scenario 1: The Growing Niche Site

**Sarah runs a 50-page affiliate site focused on outdoor gear.**

- Average monthly traffic: 15,000 sessions
- Average conversion rate: 2%
- Average commission per sale: $8
- Estimated broken links: 15-20% of total links

**Without link rot:**
- Monthly conversions: 300 sales
- Monthly commissions: $2,400
- Annual revenue: $28,800

**With 18% broken links (conservative estimate):**
- Lost monthly conversions: ~54 sales
- Lost monthly commissions: $432
- **Lost annual revenue: $5,184**

That's over $5,000 disappearing into thin air every year — from a relatively small site.

### Scenario 2: The Established Content Creator

**Mike runs a 200-page authority site in the home improvement niche.**

- Average monthly traffic: 100,000 sessions
- Average conversion rate: 1.5%
- Average commission per sale: $12
- Estimated broken links: 20-25% annually

**The damage:**
- Lost monthly conversions: ~375 sales
- Lost monthly commissions: $4,500
- **Lost annual revenue: $54,000**

Fifty-four thousand dollars. That's a full-time salary in many places, gone because of broken links.

### Industry Context

Research from across the web paints a sobering picture:

- A 2023 study found that **25% of all web links die within 5 years**
- E-commerce product pages have an even shorter lifespan — some estimates suggest **40% of product URLs become invalid within 2 years**
- Affiliate marketers who audit their sites regularly report finding **10-30% of their links are broken or suboptimal**

## The Compound Effect

Here's what makes link rot particularly insidious: it compounds over time.

Every broken link is content that's still working for you (ranking, driving traffic) but not converting. You're paying hosting fees, domain costs, and investing time into SEO — all for traffic that hits a wall.

Worse, search engines notice. When users consistently bounce from your site after hitting dead links, your engagement metrics suffer. Your rankings drop. Your traffic declines. The broken links create a cascading effect that hurts everything you've built.

## What Can You Do About It?

The solution isn't to stop using affiliate links — they're still one of the best ways to monetize content. The solution is to **monitor and maintain** those links proactively.

### Manual Audits (Small Sites)

If you have a site with fewer than 30 pages, you can manually check your links every few months. Click through each one, verify the products are still available, and update as needed. It's tedious but doable.

### Automated Monitoring (Growing Sites)

Once you scale beyond 50 pages, manual checking becomes impractical. This is where link monitoring tools become essential. They check your affiliate links automatically, alert you to problems, and help you fix issues before they cost you sales.

## LinkRescue: Your Link Rot Insurance Policy

LinkRescue was built specifically to solve this problem for affiliate marketers. Instead of wondering whether your links are working, you get:

- **Automated daily scans** of all your affiliate links
- **Instant alerts** when products go out of stock or pages break
- **Revenue impact estimates** so you know which broken links to fix first
- **Simple fix workflows** that get your commissions flowing again

Think of it as insurance for your affiliate income. For a small monthly investment, you protect the revenue you've worked hard to build.

## The Bottom Line

Link rot isn't a matter of if — it's a matter of when. Every affiliate marketer with more than a few months of content will face this issue. The question is: will you catch it early, or will you let it silently steal your commissions month after month?

Your content deserves to work as hard as you do. Don't let broken links turn your passive income stream into a trickle.

---

*Ready to stop the revenue leak? [Start your free LinkRescue trial](https://linkrescue.io) and see how many broken links are hiding on your site right now.*
$lr_silent_revenue_kille$,
  'published',
  ARRAY['linkrescue'],
  now()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  tags = EXCLUDED.tags,
  category = EXCLUDED.category,
  seo_title = EXCLUDED.seo_title,
  meta_description = EXCLUDED.meta_description,
  content = EXCLUDED.content,
  status = EXCLUDED.status,
  sites = EXCLUDED.sites,
  published_at = COALESCE(blog_posts.published_at, EXCLUDED.published_at);

INSERT INTO blog_posts (
  slug, title, author, tags, category, seo_title, meta_description, content, status, sites, published_at
) VALUES (
  'audit-site-link-rot',
  'How to Audit Your Site for Link Rot: A Complete Guide (Manual + Automated)',
  'Carson Roell',
  ARRAY['site audit','link rot','affiliate marketing','SEO tools','broken links'],
  'tutorials',
  'How to Audit Your Site for Link Rot: Manual vs Automated Methods',
  'Learn how to audit your affiliate site for broken links. Step-by-step manual process for small sites, tool recommendations, and when to use automated monitoring solutions.',
  $lr_audit_site_link_rot$You know link rot is costing you money. You've seen the estimates — potentially thousands in lost commissions every year. And the real numbers back it up: our [June 2026 Link Rot Index](/blog/link-rot-index-june-2026) (50 established affiliate sites, 6,550 links) found a median of **27 link issues per site**, with broken affiliate attribution (9.1%) outweighing visibly broken links (5.8%). Now comes the important question: how do you actually find and fix them?

This guide covers everything from manual audits for small sites to automated solutions for larger operations. By the end, you'll have a clear plan for keeping your affiliate links healthy and your revenue flowing.

## Manual Audits: The Hands-On Approach

If you run a smaller site (under 30-40 pages), manual auditing is tedious but manageable. Here's exactly how to do it:

### Step 1: Inventory Your Affiliate Content

Start by creating a complete list of every page on your site that contains affiliate links.

**Tools to help:**
- **Screaming Frog SEO Spider** (free up to 500 URLs): Crawls your site and exports all pages
- **Google Search Console**: Shows indexed pages
- **Simple spreadsheet**: List every URL with affiliate links manually

**Pro tip:** Organize by content type — product reviews, roundups, comparison posts, resource pages. This helps prioritize later.

### Step 2: Export All Affiliate Links

For each page, you need a list of every affiliate link. Here's how to get them:

**Browser Method:**
1. Visit each page
2. Right-click → Inspect Element
3. Use Ctrl+F (Cmd+F on Mac) to search for your affiliate network's domain (e.g., "amazon.com", "shareasale.com")
4. Copy each URL into your spreadsheet

**Screaming Frog Method:**
1. Crawl your site
2. Filter by "Outbound Links"
3. Export to CSV
4. Filter for affiliate domains

### Step 3: Check Each Link (The Tedious Part)

Now comes the time-consuming part — verifying each link actually works:

1. **Click every link** and verify it loads correctly
2. **Check the product is still available** — not just that the page loads, but the product can actually be purchased
3. **Note the status** in your spreadsheet:
   - ✅ Working
   - ⚠️ Redirecting (still works but worth monitoring)
   - ❌ Broken/404
   - 🚫 Out of stock
   - 🔗 Needs update (affiliate ID missing, wrong product, etc.)

**Time estimate:** 2-3 minutes per link. For a 30-page site with 5 links per page, that's 7-8 hours of work.

### Step 4: Prioritize Fixes

Not all broken links are equal. Fix them in this order:

1. **High-traffic pages first** — Check Google Analytics for your top 10 pages
2. **High-intent content** — Product reviews before general informational posts
3. **High-commission products** — Expensive items before cheap ones

### Step 5: Update or Replace

For each broken link:

**If the product is discontinued:**
- Find the closest replacement
- Update the link
- Rewrite any product-specific content as needed

**If the URL changed:**
- Update to the correct URL
- Test the new link

**If temporarily out of stock:**
- Decide: wait it out or find an alternative?
- Add a note to your calendar to check again in 2 weeks

### Step 6: Document and Schedule

Record what you fixed and when. Then schedule your next audit:

- **0-20 pages:** Every 3 months
- **20-50 pages:** Every 2 months
- **50+ pages:** Consider automation (see below)

## Free Tools for Link Auditing

If the manual approach sounds painful, these free tools can help:

### 1. Broken Link Check (brokenlinkcheck.com)

**Best for:** Quick scans of small sites

- Completely free
- Checks up to 3,000 pages
- Finds broken links but doesn't identify out-of-stock products
- No affiliate-specific features

**Limitation:** Only tells you if a page returns an error — won't catch products that are unavailable but the page still loads.

### 2. Screaming Frog SEO Spider

**Best for:** Comprehensive technical audits

- Free for up to 500 URLs
- Crawls your entire site
- Exports all outbound links
- Shows response codes (404, 301, 200, etc.)

**Limitation:** Still requires manual checking of each link to see if products are actually available.

### 3. Google Search Console

**Best for:** Identifying crawl errors

- Free with any Google account
- Shows 404 errors Google found on your site
- Limited to pages Google has crawled

**Limitation:** Only catches hard 404s, not soft failures like out-of-stock products.

### 4. Browser Extensions

**Check My Links** (Chrome): Quickly checks all links on a single page

**Link Checker** (Firefox): Similar functionality

**Best for:** Spot-checking individual pages

## Paid Tools Worth Considering

As your site grows, free tools become insufficient. Here are paid options:

### 1. Ahrefs Site Audit

- **Price:** Starting at $99/month
- **Best for:** Comprehensive SEO audits including broken links
- **Pros:** Finds broken outbound links, tracks over time, integrates with full SEO toolkit
- **Cons:** Expensive if you only need link checking; no affiliate-specific features

### 2. SEMrush Site Audit

- **Price:** Starting at $119.95/month
- **Best for:** All-in-one SEO and marketing platform
- **Pros:** Detailed broken link reports, competitive analysis
- **Cons:** Overkill for just link monitoring; not affiliate-focused

### 3. Dead Link Checker

- **Price:** Starting at $9.95/month
- **Best for:** Affordable automated checking
- **Pros:** Cheaper than full SEO suites, automated recurring checks
- **Cons:** Basic functionality; doesn't check if products are actually available

## The Problem with Generic Tools

Here's the challenge: most link checking tools — free or paid — have a critical blind spot for affiliate marketers.

They can tell you if a page returns a 404 error. They cannot tell you:

- If the product is out of stock
- If your affiliate tracking is working
- If the price changed dramatically
- If the product was replaced with a newer model
- If your affiliate link is still properly attributed

For affiliate marketers, a "200 OK" response means nothing if the product isn't actually buyable.

## When to Use LinkRescue

Manual audits and generic tools work for small sites, but there comes a point where you need specialized help.

**Consider LinkRescue when:**

✅ You have more than 50 pages with affiliate links
✅ You manage multiple sites
✅ You publish new content regularly (weekly or more)
✅ You want to catch problems within 24 hours, not months
✅ You need to know if products are actually available, not just if pages load
✅ You're losing track of which links you've checked and when

### What LinkRescue Does Differently

Unlike generic link checkers, LinkRescue is built specifically for affiliate marketers:

**Affiliate-Specific Monitoring:**
- Checks if products are actually available, not just if URLs work
- Verifies affiliate tracking parameters are present
- Monitors Amazon's frequently changing URL structures

**Revenue Impact Analysis:**
- Shows which broken links are on your highest-traffic pages
- Estimates potential lost commissions
- Helps you prioritize fixes by revenue impact

**Automated Workflows:**
- Daily scans of your entire site
- Instant Slack/email alerts when problems are found
- One-click fix suggestions

**Designed for Scale:**
- Handles thousands of pages
- Tracks link health over time
- Generates reports for stakeholders or clients

## Making the Decision: Manual vs. Automated

Here's a simple framework:

| Site Size | Method | Time Investment | Cost |
|-----------|--------|-----------------|------|
| 1-20 pages | Manual audit | 4-6 hours/quarter | Free |
| 20-50 pages | Manual + free tools | 8-10 hours/quarter | Free-$20/month |
| 50-200 pages | Hybrid or LinkRescue | 2-4 hours/month + tool | $29-79/month |
| 200+ pages | LinkRescue or enterprise | 1-2 hours/month | $79-299/month |

**The break-even point:** If your site generates more than $1,000/month in affiliate commissions, broken links are almost certainly costing you more than $29/month in lost revenue.

## Your Action Plan

**This week:**
1. Do a quick manual check of your top 10 most-trafficked pages
2. Count how many affiliate links you have total
3. Note how many are broken or questionable

**This month:**
1. Decide on your audit frequency based on site size
2. Choose your method (manual, free tools, or LinkRescue)
3. Schedule your first full audit

**Ongoing:**
1. Monitor new content as you publish it
2. Review and fix broken links on your schedule
3. Track revenue recovery to measure impact

## Final Thoughts

Link auditing isn't glamorous work, but it's some of the highest-ROI work you can do as an affiliate marketer. Every broken link you fix is money back in your pocket — often with just a few minutes of effort.

Whether you choose the manual route or an automated solution, the important thing is to start. Your future self (and your bank account) will thank you.

---

*Ready to automate your link monitoring? [Try LinkRescue free for 14 days](https://linkrescue.io) and discover every broken link on your site in minutes, not hours.*
$lr_audit_site_link_rot$,
  'published',
  ARRAY['linkrescue'],
  now()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  tags = EXCLUDED.tags,
  category = EXCLUDED.category,
  seo_title = EXCLUDED.seo_title,
  meta_description = EXCLUDED.meta_description,
  content = EXCLUDED.content,
  status = EXCLUDED.status,
  sites = EXCLUDED.sites,
  published_at = COALESCE(blog_posts.published_at, EXCLUDED.published_at);

-- Verify
SELECT slug, title, status, published_at FROM blog_posts ORDER BY published_at DESC;

-- ============================================================
-- BONUS (migration 017): Gate-2 funnel counts RPC for the Foreman heartbeat.
-- Safe to re-run (CREATE OR REPLACE). After this runs, the JARVIS Dispatcher
-- shows live "X/100 scans - first paid" numbers every 3h.
-- ============================================================
create or replace function public.funnel_counts()
returns json
language sql
stable
security definer
set search_path = public
as $func$
  select json_build_object(
    'scans',  (select count(*) from public.free_scan_results where created_at >= '2026-07-01'),
    'emails', (select count(*) from public.free_scan_leads   where created_at >= '2026-07-01' and email is not null),
    'paid',   (select count(*) from public.users
               where stripe_subscription_id is not null
                 and stripe_current_period_end > now())
  );
$func$;

revoke all on function public.funnel_counts() from public;
grant execute on function public.funnel_counts() to anon;

SELECT public.funnel_counts() AS gate2_baseline;
