#!/usr/bin/env node
/**
 * Render the monthly Link Rot Index data sections as markdown.
 * Reads aggregate-summary.json + raw results/, prints markdown to stdout.
 *
 * Usage: node render-index.js [results-dir] [summary-file]
 * Defaults: ./results ./aggregate-summary.json
 *
 * Monthly flow: bash run-scans.sh -> node aggregate.js -> node render-index.js
 */

const fs = require('fs');
const path = require('path');

const RESULTS_DIR = process.argv[2] || path.join(__dirname, 'results');
const SUMMARY_FILE = process.argv[3] || path.join(__dirname, 'aggregate-summary.json');

const summary = JSON.parse(fs.readFileSync(SUMMARY_FILE, 'utf-8'));

const checked = summary.totalLinks;
const pct = (n) => ((n / Math.max(checked, 1)) * 100).toFixed(1);

// aggregate.js already separates bot-blocked (403/405/429) from broken
const hardDead = summary.errorBreakdown.broken4xx;
const blocked = summary.errorBreakdown.blocked ?? 0;
const serverErr = summary.errorBreakdown.server5xx;
const timeouts = summary.errorBreakdown.timeout;
const lostParams = summary.errorBreakdown.lostParams;
const redirectHome = summary.errorBreakdown.redirectToHome;
const attributionIssues = lostParams + redirectHome;

const monthName = new Date(summary.scanDate).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

console.log(`<!-- Generated by render-index.js from scan of ${summary.scanDate} -->`);
console.log(`## The ${monthName} numbers\n`);
console.log(`We scanned **${summary.sitesScanned} well-known affiliate sites** (${summary.totalPages} pages, **${checked.toLocaleString()} outbound links checked**) on ${new Date(summary.scanDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}.\n`);
console.log(`| What we found | Links | % of checked |`);
console.log(`|---|---|---|`);
console.log(`| Broken links (4xx - page gone or invalid) | ${hardDead.toLocaleString()} | ${pct(hardDead)}% |`);
console.log(`| Server errors (5xx) | ${serverErr.toLocaleString()} | ${pct(serverErr)}% |`);
console.log(`| Timeouts (no answer in 10s) | ${timeouts.toLocaleString()} | ${pct(timeouts)}% |`);
console.log(`| **Affiliate tracking stripped (params lost)** | **${lostParams.toLocaleString()}** | **${pct(lostParams)}%** |`);
console.log(`| Redirects to homepage (offer gone) | ${redirectHome.toLocaleString()} | ${pct(redirectHome)}% |`);
console.log(`| Bot-blocked / unverifiable by automated checkers (403/405/429) | ${blocked.toLocaleString()} | ${pct(blocked)}% |`);
console.log('');
console.log(`**Attribution failures alone (stripped params + homepage redirects): ${attributionIssues.toLocaleString()} links - ${pct(attributionIssues)}% of every link checked.** These return healthy status codes. No generic link checker flags them. The commission just quietly stops.\n`);

console.log(`### Per-site reality\n`);
console.log(`- Median issues per site: **${summary.medianAllIssuesPerSite}**`);
console.log(`- Sites with zero broken links: **${summary.zeroBrokenSites} of ${summary.sitesScanned}**`);
console.log(`- Worst site we scanned: **${summary.worstBroken} broken links** (${summary.worstSite})`);
console.log('');

console.log(`### By niche (issue rate on checked links)\n`);
console.log(`| Niche | Sites | Links checked | Issues | Rate |`);
console.log(`|---|---|---|---|---|`);
const niches = Object.entries(summary.byNiche)
  .map(([name, ns]) => ({ name, ...ns, rate: (ns.broken + ns.lostParams) / Math.max(ns.links, 1) }))
  .sort((a, b) => b.rate - a.rate);
for (const n of niches) {
  console.log(`| ${n.name} | ${n.sites} | ${n.links.toLocaleString()} | ${n.broken + n.lostParams} | ${(n.rate * 100).toFixed(1)}% |`);
}
console.log('');

console.log(`### The ten leakiest sites this month\n`);
console.log(`| Site | Links checked | HTTP broken | Attribution issues |`);
console.log(`|---|---|---|---|`);
const worst = summary.perSite
  .filter((r) => r.status === 'ok')
  .sort((a, b) => b.allIssues - a.allIssues)
  .slice(0, 10);
for (const s of worst) {
  console.log(`| ${s.site} | ${s.links} | ${s.brokenHttp} | ${s.affiliateIssues} |`);
}
console.log('');

console.log(`### Methodology\n`);
console.log(`- ${summary.sitesScanned}/50 target sites scanned (${summary.sitesPartialBudget ?? 0} returned partial results under a 100-second per-site budget).`);
console.log(`- ${summary.totalLinksFound?.toLocaleString() ?? 'n/a'} outbound links found; ${checked.toLocaleString()} checked within budget. All rates are computed on checked links only.`);
console.log(`- Every link was requested with HEAD, retried with GET on suspicious responses, redirects followed up to 5 hops, and tracking parameters compared on the final URL.`);
console.log(`- Bot-blocked responses (403/405/429 after a GET retry) are reported separately and are NOT counted as broken.`);
console.log(`- Scanner: the same open crawler that powers LinkRescue (npx linkrescue).`);
